#!/bin/bash

echo "🔐 Vercel 환경 변수 설정 가이드"
echo "================================"
echo ""
echo "1️⃣ Vercel 대시보드로 이동:"
echo "   https://vercel.com/dashboard"
echo ""
echo "2️⃣ 프로젝트 선택 후 Settings 탭 클릭"
echo ""
echo "3️⃣ Environment Variables 섹션으로 이동"
echo ""
echo "4️⃣ 다음 환경 변수들을 추가:"
echo ""
echo "   Name: SUPABASE_URL"
echo "   Value: https://fvfqzhmqfiuctelppaeh.supabase.co"
echo "   Environments: Production, Preview, Development"
echo ""
echo "   Name: SUPABASE_ANON_KEY"  
echo "   Value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ2ZnF6aG1xZml1Y3RlbHBwYWVoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMwMzc3NzIsImV4cCI6MjA3ODYxMzc3Mn0.c2HeYl2lI0QauIdBM7QhLXc-tiJ8rm6adQAFLN4wVHM"
echo "   Environments: Production, Preview, Development"
echo ""
echo "5️⃣ Save 버튼 클릭"
echo ""
echo "6️⃣ 프로젝트 재배포:"
echo "   Deployments 탭 → 최신 배포 → ... → Redeploy"
echo ""
echo "✅ 완료! 이제 API 키가 안전하게 분리되어 배포됩니다."
echo ""
echo "🔍 테스트 방법:"
echo "   - 배포된 사이트 방문"
echo "   - 브라우저 개발자 도구 콘솔에서 '프로덕션 환경 변수 로드됨' 메시지 확인"
echo "   - 게임 완료 후 리더보드에 점수가 정상적으로 저장되는지 확인"